/** 游戏资源路径（相对 index.html） */
const ASSETS = {
  audio: {
    title: "assets/audio/bgm-title.mp3",
    story: "assets/audio/bgm-story.mp3",
    angst: "assets/audio/bgm-angst.mp3",
    ending: "assets/audio/bgm-ending.mp3",
  },
  hero: "assets/images/hero-xiaozhan-cutout.png",
  heroine: "assets/images/heroine-isapara-cutout.png",
  bg: {
    title: "assets/images/bg/bg-gallery.png",
    studio: "assets/images/bg/bg-studio.png",
    gallery: "assets/images/bg/bg-gallery.png",
    rain: "assets/images/bg/bg-rain-night.png",
    backstage: "assets/images/bg/bg-backstage.png",
    dawn: "assets/images/bg/bg-dawn.png",
    cafe: "assets/images/bg/bg-cafe-photo.jpg",
    museum: "assets/images/bg/bg-museum.jpg",
    nightcity: "assets/images/bg/bg-night-city.jpg",
    party: "assets/images/bg/bg-party.jpg",
    salon: "assets/images/bg/bg-salon.jpg",
    rooftop: "assets/images/bg/bg-rooftop-bar.jpg",
    recording: "assets/images/bg/bg-recording.jpg",
    office: "assets/images/bg/bg-studio.png",
    stage: "assets/images/bg/bg-gallery.png",
    concert: "assets/images/bg/bg-backstage.png",
    street: "assets/images/bg/bg-rain-night.png",
    home: "assets/images/bg/bg-studio.png",
    exhibition: "assets/images/bg/bg-gallery.png",
  },
  npc: {
    boss: "assets/images/npc/npc-boss-cutout.png",
    colleague: "assets/images/npc/npc-colleague-cutout.png",
    fan: "assets/images/npc/npc-fan-cutout.png",
    reporter: "assets/images/npc/npc-reporter-cutout.png",
    agent: "assets/images/npc/npc-agent-cutout.png",
    curator: "assets/images/npc/npc-curator-cutout.png",
    landlord: "assets/images/npc/npc-landlord-cutout.png",
    bestie: "assets/images/npc/npc-bestie-cutout.png",
    zhangyixing: "assets/images/npc/npc-zhangyixing-cutout.png",
    songweilong: "assets/images/npc/npc-songweilong-cutout.png",
    gongjun: "assets/images/npc/npc-gongjun-cutout.png",
    yangmi: "assets/images/npc/npc-yangmi-cutout.png",
    nini: "assets/images/npc/npc-nini-cutout.png",
    yangzi: "assets/images/npc/npc-yangzi-cutout.png",
    default: "assets/images/npc/npc-colleague-cutout.png",
  },
};

/** 角色资料 */
const CHARACTERS = {
  isapara: {
    name: "isapara",
    role: "女主 · 独立艺术工作室主理人",
    desc: "职工家庭独生女，美院毕业后开了间工作室。常作伴的是蓝猫「卷卷」。",
  },
  juanjuan: { name: "卷卷", role: "女主的猫 · 蓝猫", desc: "可爱、胖、蓝灰色短毛。" },
  xiaozhan: { name: "肖战", role: "男主 · 顶流巨星", desc: "设计师出身，私下爱画画，感情克制温柔。" },
  liujie: { name: "刘姐", role: "经纪人 / 表姐", desc: "冷艳干练，暗中护着肖战与画展。" },
  zhangyixing: { name: "张艺兴", role: "可攻略 · 歌手演员", desc: "沉稳温和，用音乐接住你的雨。" },
  songweilong: { name: "宋威龙", role: "可攻略 · 演员", desc: "清爽直接，把你的画当成全世界。" },
  gongjun: { name: "龚俊", role: "支线 · 时尚偶像", desc: "明亮爱笑，在薇薇的策展里撞进缘分。" },
  yangmi: { name: "杨幂", role: "演员 / 制作人", desc: "反应快，护短。" },
  nini: { name: "倪妮", role: "演员 · 时尚圈好友", desc: "气场强，夸人很准。" },
  yangzi: { name: "杨紫", role: "演员", desc: "活泼，爱八卦但心不坏。" },
  vivi: { name: "薇薇", role: "闺蜜 · 策展助理", desc: "比你还敢问，手机存着半个娱乐圈。" },
};
